# Generated by Django 5.0.6 on 2024-07-05 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(default='', max_length=50)),
                ('phone', models.CharField(default='', max_length=50)),
                ('desc', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('allDesc', models.CharField(default='', max_length=300)),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('phone', models.CharField(default='', max_length=15)),
                ('alternate_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.CharField(default='', max_length=255)),
                ('address2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(default='', max_length=100)),
                ('state', models.CharField(default='', max_length=100)),
                ('pin', models.CharField(default='', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('allSize', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('Fullsleeves', 'fullsleeves'), ('Hoodie', 'hoodie'), ('T-shirts', 't-Shirt')], default='T-shirts', max_length=50)),
                ('color', models.CharField(default='', max_length=50)),
                ('size', models.CharField(blank=True, default='', max_length=50)),
                ('size_1st', models.CharField(blank=True, choices=[('M,', 'M'), ('L,', 'L'), ('XL,', 'XL'), ('XXL,', 'XXL')], default='', max_length=50)),
                ('size_2nd', models.CharField(blank=True, choices=[('M,', 'M'), ('L,', 'L'), ('XL,', 'XL'), ('XXL,', 'XXL')], default='', max_length=50)),
                ('size_3rd', models.CharField(blank=True, choices=[('M,', 'M'), ('L,', 'L'), ('XL,', 'XL'), ('XXL,', 'XXL')], default='', max_length=50)),
                ('size_4th', models.CharField(blank=True, choices=[('M,', 'M'), ('L,', 'L'), ('XL,', 'XL'), ('XXL,', 'XXL')], default='', max_length=50)),
                ('discount', models.CharField(default='', max_length=50)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('image', models.ImageField(default='', upload_to='shop/images')),
                ('desc', models.CharField(max_length=300)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
