# Generated by Django 5.0.6 on 2024-07-24 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_outofstock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='imageTwo',
            field=models.ImageField(default='', upload_to='shop/images'),
        ),
    ]
