# Generated by Django 5.0.6 on 2024-07-25 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_imagetwo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Fullsleeves', 'fullsleeves'), ('Hoodie', 'hoodie'), ('T-shirts', 't-Shirt'), ('gift', 'gift')], default='T-shirts', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='outOfStock',
            field=models.CharField(blank=True, choices=[('Out Of Stock', 'Out Of Stock')], default='', max_length=50),
        ),
    ]
