# Generated by Django 5.0.6 on 2024-07-26 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_product_category_alter_product_outofstock'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='img',
            field=models.ImageField(default='', upload_to='shop/images'),
        ),
    ]
