# Generated by Django 5.0.6 on 2024-07-27 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_order_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='img',
        ),
        migrations.AddField(
            model_name='order',
            name='imgPath',
            field=models.CharField(default='', max_length=300),
        ),
    ]
