# Generated by Django 5.0.6 on 2024-07-28 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_remove_order_img_order_imgpath'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='option',
            field=models.CharField(default='', max_length=50),
        ),
    ]
